USE codeup_test_db;
INSERT INTO albums (`artist_name`, `name`, `release_date`, `genre`, `sales`)
VALUES ('Michael Jackson', 'Thriller', 1982, 'Pop/Post-Disco/Funk/Rock', 70),
('AC/DC', 'Back in Black', 1980, 'Hard Rock', 50),
('Whitney Houston', 'The Bodyguard', 1992, 'R&B/Soul/Pop/Soundtrack', 45),
('Meat Loaf', 'Bat Out of Hell', 1977, 'Hard Rock/Glam Rock/Progressive Rock', 45),
('Eagles', 'Their Greatest Hits 1971-1975', 1976, 'Country Rock/Soft Rock/Folk Rock', 44),
('Pink Floyd', 'The Dark Side of the Moon', 1973, 'Progressive Rock', 44),
('Eagles', 'Hotel California', 1976, 'Soft Rock', 42),
('Bee Gees', 'Saturday Night Fever', 1977, 'Disco', 40),
('Fleetwood Mac', 'Rumours', 1977, 'Soft Rock', 40),
('Shania Twain', 'Come On Over', 1997, 'Country/Pop', 40),
('Various artists', 'Grease: The Original Soundtrack from the Motion Picture', 1978, 'Soundtrack', 38),
('Led Zeppelin', 'Led Zeppelin IV', 1971, 'Hard Rock/Heavy Metal/Folk', 37),
('Michael Jackson', 'Bad', 1987, 'Pop/Funk/Rock', 35),
('Alanis Morissette', 'Jagged Little Pill', 1995, 'Alternative Rock', 33),
('Michael Jackson', 'Dangerous', 1991, 'New Jack Swing/R&B/Pop', 32),
('Celine Dion', 'Falling into You', 1996, 'Pop/Soft Rock', 32),
('The Beatles', 'Sgt. Peppers Lonely Hearts Club Band', 1967, 'Rock', 32),
('Various artists', 'Dirty Dancing', 1987, 'Pop/Rock/R&B', 32),
('Adele', '21', 2011, 'Pop/Soul', 31),
('Celine Dion', 'Let''s Talk About Love', 1997, 'Pop/Soft Rock', 31),
('Metallica', 'Metallica', 1991, 'Thrash Metal/Heavy Metal', 31),
('The Beatles', '1', 2000, 'Rock', 31),
('The Beatles', 'Abbey Road', 1969, 'Rock', 31),
('ABBA', 'Gold: Greatest Hits', 1992, 'Pop/Disco', 30),
('Bruce Springsteen', 'Born in the U.S.A.', 1984, 'Rock', 30),
('Madonna', 'The Immaculate Collection', 1990, 'Pop/Dance', 30),
('Pink Floyd', 'The Wall', 1979, 'Progressive Rock', 30),
('James Horner', 'Titanic: Music from the Motion Picture', 1997, 'Soundtrack', 30),
('Dire Straits', 'Brothers in Arms', 1985, 'Rock/Pop', 30),
('Nirvana', 'Nevermind', 1991,' Grunge/Alternative Rock', 30),
('Santana', 'Supernatural', 1999, 'Rock', 30),
('Guns N Roses', 'Appetite for Destruction', 1987, 'Hard Rock', 30);
